name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: Go to correct directory
        run: cd go/bk1/ch1/
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test
