name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: List the contents of the current directory
        run: ls -la
      - name: Install dependencies
        run: go get .
        working-directory: go/bk1/ch1/
      - name: Test with the Go CLI
        run: go test
        working-directory: go/bk1/ch1/

      - name: Test all directories where we have a go mod file
        run: |
          find . -type f -name "go.mod" -exec dirname {} \; | sort -u | while read dir; do
            echo "Processing Go module in: $dir"
            cd "$dir"
            go get .
            go test ./...
            cd -
          done
