name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: List the contents of the current directory
        run: ls -la
      - name: Install dependencies
        run: go get .
        working-directory: go/bk1/ch1/
      - name: Test with the Go CLI
        run: go test
        working-directory: go/bk1/ch1/
